### ISSUE TITLE
Feature Request: Scroll workspace wraparound

### ISSUE THREAD

**Issue by rivenirvana** [christopher-l/space-bar#10]
Similar to Dotspaces

**Comment by Morikko** [comment]
https://extensions.gnome.org/extension/1116/workspace-switch-wraparound/ does it when using the gnome keyboard shortcuts but it does not work with the scroll of this extension.

The extension is tweaking `Meta.Workspace.prototype.get_neighbor`, the scroll may inherit the behavior if it does call that function.

**Comment by christopher-l** [comment]
Hi @rivenirvana and @Morikko, thanks for the request and the hint.
I implemented a wrap-around option with the latest release (v19).
![image](https://github.com/christopher-l/space-bar/assets/1208506/7dbc68c1-c74e-49b6-8f79-2649707b949a)

**Comment by rivenirvana** [comment]
Can confirm, thanks for the implementation!
