### ISSUE TITLE
Feature Request: Font Size

### ISSUE THREAD

**Issue by iworkinpixels** [christopher-l/space-bar#11]
I used a Nerd Font to create icons of my workspaces for the labels, but that means that If I want the icons to match the size of the rest of the icons in my topbar I need to be able to customize the font size for this extension.

Could you add another textbox or dropdown on the appearance screen to allow me to do so? 

Thank you.

**Comment by 31KM** [comment]
Could explain how you changed the font for Space Bar?

**Comment by iworkinpixels** [comment]
In Gnome Tweaks, I set all the fonts to a NerdFont (MesloLGS NF), thus enabling me to set my workspace names to the appropriate icons, like so:

![Screenshot from 2023-07-14 16-59-51](https://github.com/christopher-l/space-bar/assets/1134283/126e11c8-c33c-4b17-8c82-7f4225d2c23e)

**Comment by iworkinpixels** [comment]
UPDATE: I did figure out a fix that does work, although it's inelegant...

But since I have only one thing in the center panel, I can just edit my gnome shell theme and set the following:

```
#panelCenter {
    font-size: 18px;
}
```

That having been said, a lot of people aren't going to have it isolated like that and so the feature would still be useful.

**Comment by christopher-l** [comment]
Hey everyone, thanks for the feedback!

I implemented an option for choosing the font size. It is included in the upcoming release (v20).
