### ISSUE TITLE
Feature Request: Show icons in their respective WS

### ISSUE THREAD

**Issue by brunnogama** [christopher-l/space-bar#15]
Hey, great extension, thanx!

Is there any way to show the open app icon right after your respective workspace?
For example, I have app A on WS 1, apps B C on WS 2 and D E on WS 3 and could be this way:

[1] A [2] B C [3] D E

Now it shows like this:
[1] [2] [3] A B C D E

I dont know if I did a good explain (my english is not so good).

**Comment by christopher-l** [comment]
Hi @brunnogama, you are referring to the extension [App Icons Taskbar](https://extensions.gnome.org/extension/4944/app-icons-taskbar/) right?

I think this is a bit outside the scope of this extension. There used to be the extensions [BaBar](https://extensions.gnome.org/extension/4000/babar/) and [BaBar Lite](https://extensions.gnome.org/extension/4681/babar-task-bar-lite-for-gnome-40/), which aren't maintained anymore, and now there is [Workspaces indicator by open apps](https://extensions.gnome.org/extension/5967/workspaces-indicator-by-open-apps/), all of which provide behavior as you describe. Another extension like these is probably the way to go for this.
