### ISSUE TITLE
Feature Request: setting to invert the scrolling

### ISSUE THREAD

**Issue by thyttan** [christopher-l/space-bar#17]
Hi, thanks for this extension, I'm trying it out and think I will stick with it!

I find the scrolling is counter to my intution. I expect to go to a higher number workspace by draging my fingers top-to-bottom on my touchpad. I'd like to be able to configure this.

Maybe adding the option of scrolling horizontally (I'd prefer "natural" scrolling here) would make sense as well.

Cheers!

EDIT: I just noticed chromium browser uses the same two finger scrolling behavior for tab scrolling if the cursor is positioned on the tab bar as it is implemented for space-bar.  I'd still appreciate the option though.

**Comment by christopher-l** [comment]
Hi @thyttan, thanks for the feature request!

I implemented options for inverting the scroll direction and for horizontal scrolling. They are included with the upcoming release (v20).
