### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [christopher-l/space-bar#20]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by christopher-l** [comment]
I started a branch for migration to GNOME 45: https://github.com/christopher-l/space-bar/tree/gnome45.

So far, things seem to be working, but I haven't tested outside of a VM yet.

**Comment by yochananmarqos** [comment]
It's working well, thank you. 

Could you add an option to hide the new Activities Indicator? It looks very simple, see the [HideActivies](https://github.com/zeten30/HideActivities/) extension.

**Comment by christopher-l** [comment]
The release that migrates to Gnome 45 is currently pending review. The extension should upgrade to the compatible version when it is accepted.
