### ISSUE TITLE
Feature Request: Add option to display the workspace index in the top bar

### ISSUE THREAD

**Issue by johannesCmayer** [christopher-l/space-bar#21]
Hi, very nice extension.

I would like to be able to see the index of the current workspace, such that I can use keyboard shortcuts to navigate to the correct workspace. Without this, I might not be able to get the keyboard shortcut right if I have more than 10 workspaces and frequently rearrange them.

I would expect that this should be pretty easy to do.

If I have a workspace named `Write`  the top bar should display `12:Write` if the workspace is at the 12th position. Or something like this.

**Comment by christopher-l** [comment]
I added an option for this.
![image](https://github.com/christopher-l/space-bar/assets/1208506/6ec08459-9c0b-4e44-96d7-beb7f7293f74)
