### ISSUE TITLE
Show only current workspace name

### ISSUE THREAD

**Issue by karypid** [christopher-l/space-bar#24]
In General setting of Behaviour, there is a toggle to "Show empty workspaces". I would love it if there was a similar switch to "Show only current workspace" which can default  to false for backwards compatibility. If this were selected, rather than showing all workspace names, you would only show the name of the active workspace (it would change as you change workspace).

I use 7 workspaces so a lot of space is wasted by showing all of them...

**Comment by christopher-l** [comment]
I added an option that replaces the indicator with a simple label that shows the current workspace's name.

![image](https://github.com/christopher-l/space-bar/assets/1208506/d95a80d8-ee43-4f7c-8a34-cf90a91d0d38)

**Comment by karypid** [comment]
This is exactly what I was after. Just tested the new version and it works great. Thank you!
