### ISSUE TITLE
Prevent the cutting of of names when there is still space

### ISSUE THREAD

**Issue by johannesCmayer** [christopher-l/space-bar#27]
Check out this image.:
![image](https://github.com/christopher-l/space-bar/assets/24253624/a0b13ed5-fca7-450c-882b-6df627318ab7)

It seems like there is still a lot of space in the top bar, but the text already gets cut off. Would it be possible to adjust space-bar such that it uses the entirety of the available space before cutting off the workspace names? 

I am on Pop!_OS.

**Comment by christopher-l** [comment]
It looks like there is still space reserved for a central widget. Did you use an extension to move the clock to the right?

**Comment by johannesCmayer** [comment]
Probably. I use pop-os, and in the option, there is a setting to move the clock to the right, which is toggled.
