### ISSUE TITLE
Feature Request: Move new application's windows to specific workspace

### ISSUE THREAD

**Issue by HM-Huong** [christopher-l/space-bar#28]
Could you create a feature to group several applications into one group? These groups have priority order, when opening an application of a low-priority group, it will be in the workspace after the higher-priority group. For example, I have:

- Group 1: vs code
- Group 2: chrome, terminal
- Group 3: gnome text editor

and the priority order of the groups is: group 1 > group 2 > group 3

- Initially, when I open the gnome text editor it will be in workspace 1
- Next, I open the terminal, the gnome text editor will be moved to workspace 2, and the terminal will be in workspace 1.
- If I open the Chrome browser, it will be in the same workspace as the terminal.
- If I continue to open vs code it will be in workspace 1. The terminal and the Chrome browser will be in workspace 2. The gnome text editor will be in workspace 3.
- If I open any application that is not in the above groups, it will be in the workspace I am currently using and temporarily linked to that group.
- If I move a window from one group's workspace to another group, that window's priority will temporarily be the priority of the group it moved to (the application's window will be temporarily linked with the group it moves to)
- The workspace that doesn't contain any group can be placed anywhere.

I know it's a complicated feature, but I couldn't find any extension that does this.

I really hope you'll add this feature. Sincerely thank you!

**Comment by SebTM** [comment]
This already exists as separate extension: https://ubuntuhandbook.org/index.php/2022/08/app-start-certain-workspace-gnome/ which is part of the [gnome-shell-extensions](https://gitlab.gnome.org/GNOME/gnome-shell-extensions)

**Comment by HM-Huong** [comment]
I have tried that extension, but it will create some new empty workspace. For example, if I assign Chrome to workspace 4 and vs code to workspace 1 (and some other app in workspace 2 and 3). Then, for some reason, I only need to open vscode and chrome, it will create 2 new empty workspaces 2 and 3. It will be a bad experience when using the "switch workspaces with scroll wheel" feature.

**Comment by christopher-l** [comment]
Hi @HM-Huong, thanks for the request!

However, if I understand you correctly, the feature you would like is about moving windows to existing workspaces. This would probably better be implemented in a separate extension since it is a separate feature.

In case this is of any help: you could use the Auto-move-windows extension und disable "Show empty workspaces" in the Space-bar extension. This way, the empty workspaces will be skipped when switching workspaces with the scroll wheel.
