### ISSUE TITLE
Feature Request: Add option to leave System Workspace Indicator visible

### ISSUE THREAD

**Issue by nleanba** [christopher-l/space-bar#29]
Hi! I love the extension, but I have the following request:

It would be really nice to have the option to unhide the system workspace indicator (formerly Activities button), even when the space bar is on the left.

Usecase: I have many workspaces and only want to show the current workspace name for not-enough-space reasons (As was enabled https://github.com/christopher-l/space-bar/issues/24). However, this loses the visual indication as to “where” in the row of workspaces I am. The new (Gnome 45) workspace indicator provides that, but it gets hidden if the space bar is on the left side (https://github.com/christopher-l/space-bar/blob/main/src/services/TopBarAdjustments.ts#L23).

With both the “Show only current workspace name” and the new “Don't hide System Workspace indicator” enabled, one could get the best of both worlds for small screens: Visual indication and names for workspaces.

**Comment by christopher-l** [comment]
Hi @nleanba, thanks for the request.

I added an option to the extended settings of "Position in top panel"
![image](https://github.com/christopher-l/space-bar/assets/1208506/1828425a-fd09-41b8-a28d-b7045417a7f5)

The release is currently pending review.

**Comment by nleanba** [comment]
Thanks!

This is exactly what I wanted
