### ISSUE TITLE
Doesn't work with touch displays

### ISSUE THREAD

**Issue by lukgreen** [christopher-l/space-bar#30]
Clicking on workspace numbers or names on a touch display doesn't work.

**Comment by christopher-l** [comment]
Hi @lukgreen, thanks for the report!

I tried to add support for touch events, but I don't own a touchscreen device. Could you test the following features:
- Single tap should switch to the workspace as a left click does.
- Long press should open the menu.

I didn't write any code to support drag-and-drop. Could you also check, if this interferes in any way?

To install the updated version, download https://github.com/christopher-l/space-bar/raw/feat/touch-events/space-bar@luchrioh.shell-extension.zip and run the following command inside the containing directory:
```sh
gnome-extensions install --force space-bar@luchrioh.shell-extension.zip
```

Thanks for your help!

**Comment by lukgreen** [comment]
It works.

**Comment by christopher-l** [comment]
Thanks for testing! Merged and submitted to extensions.gnome.org. Note that touch support is introduced with the newest version of the extension (25), which is only compatible to GNOME 46.
