### ISSUE TITLE
Support for Gnome 46

### ISSUE THREAD

**Issue by nightsh** [christopher-l/space-bar#35]
Hi and thanks for the great work you're doing :-) 
I've been using this extension until yesterday, when Gnome 46 became available in Tumbleweed repos. 
Now I'm getting the "incompatible" message:

![image](https://github.com/christopher-l/space-bar/assets/1579997/69c707f9-e6ea-4276-a762-cd3a61a7fd49)

I'm not sure if compatibility is limited by just a version number, or there are other breaking changes in the 46 release, but I'd be happy to try it out, if you would lay out some steps for me to follow.

Thanks!

**Comment by maxgreene123** [comment]
If you compile from source and change the gnome version from 45 to 46 in the metadata.json and install it works perfectly.

**Comment by akhilesh-w** [comment]
@maxgreene123 so can you not just make a pull request with this change so that everybody can use it?

**Comment by maxgreene123** [comment]
Oh yeah your right lol. I just opened the pull request with the update for gnome 46.

**Comment by christopher-l** [comment]
Accepted the PR, thank you!

I'm AFK for some days, will submit the updated extension when back.

**Comment by yochananmarqos** [comment]
@christopher-l I think you forgot to bump Mutter, etc. from 13 to 14 in the `build.sh`. :wink:

**Comment by yochananmarqos** [comment]
@christopher-l Oh yes, sorry. :laughing:

**Comment by christopher-l** [comment]
Updated the types and submitted to extensions.gnome.org.

I ended up removing support for GNOME 45 again since the type updates indicated some breaking changes that I had to adapt to.
