### ISSUE TITLE
[FEATURE REQUEST] Show names only on overview

### ISSUE THREAD

**Issue by uacode** [christopher-l/space-bar#38]
Hello, can you add please option to show WS names only on overview or overview + names under the photo

https://i.imgur.com/0FapRko.png

P.S. Cool extension!

**Comment by christopher-l** [comment]
Hi @uacode, I'm glad you like the extension. :)

However, as explained in https://github.com/christopher-l/space-bar/issues/32, that is outside the scope I want to keep the extension in.

**Comment by uacode** [comment]
Sorry for duplicate

**Comment by christopher-l** [comment]
No problem :)
