### ISSUE TITLE
[FEATURE REQUEST] Multi-monitor support

### ISSUE THREAD

**Issue by 34code** [christopher-l/space-bar#41]
I would like to be able to see a separate switcher per monitor...

**Comment by 34code** [comment]
Reading the README further, the project advertises multi-monitor support but im unable to see any options in the gui for enabling/disabling said multi-monitor support..

**Comment by christopher-l** [comment]
There is no multi-monitor support in the way that it could be enabled or disabled. The extension has been developed with multi-monitor setups in mind and takes care to not break in this case. Maybe that should be clearer in the README.

As for your request, I also would very much like to have this, but that would take quite some modifications to the way GNOME handles workspaces. [PaperWM](https://extensions.gnome.org/extension/6099/paperwm/) does this, and there used to be another extension, which did only this, that I can't find at the moment. However, I have not seen an implementation that worked really well yet. For now, I'm sad to say that this exceeds the scope of this extension.

**Comment by 34code** [comment]
Got it, thanks for introducing me to PaperWM!
