### ISSUE TITLE
GNOME 47 Support

### ISSUE THREAD

**Issue by tareqimbasher** [christopher-l/space-bar#45]
The extension is not compatible with GNOME 47. This is an extension I use constantly. Would appreciate an update. Thank you for your for this awesome extension!

**Comment by 1337hero** [comment]
All you need to do is go into `~/.local/share/gnome-shell/extensions/`

And edit the metadata.json
`"shell-version": [
  "45",
  "46",
  "47"
]
`
In my testing and looking at the changelog there is no reason for this to not work on 47 and is working for me.

**Comment by tareqimbasher** [comment]
Thanks @1337hero! I can confirm that works.

**Comment by christopher-l** [comment]
Thanks for testing! Merged https://github.com/christopher-l/space-bar/pull/46.
