### ISSUE TITLE
Custom font size for placeholder text

### ISSUE THREAD

**Issue by DodoLeDev** [christopher-l/space-bar#47]
Hi!

First and foremost, **thank you for your great work on this extension!**

Because I just love so much the initial design by GNOME, I customized my extension to make it identical:

![image](https://github.com/user-attachments/assets/4805d618-77a3-4d8e-bfac-2070ebfb10d7)

However, a little problem appears when my workspace has no name:

|GNOME| SpaceBar |
|:---:|:---:|
| ![image](https://github.com/user-attachments/assets/0e9a5ccc-ac10-4735-8949-1b1ee26111d0) <br> _Looks clean_ | ![image](https://github.com/user-attachments/assets/b6a61fac-f0cd-4a88-9a73-53d71cb99681) <br> _The pill is kinda big..._|

Do you think it would be possible to add a little setting to change the font size only for the placeholder text? (mine is a bunch of spaces)

**Comment by christopher-l** [comment]
Hi @DodoLeDev!

I think I found a way to enable this. I uploaded an experimental version of the extension here: https://github.com/christopher-l/space-bar/raw/refs/heads/feat/custom-styles/space-bar@luchrioh.shell-extension.zip.

You can install with
```sh
gnome-extensions install --force space-bar@luchrioh.shell-extension.zip
```
and then logging out and in again.

What this does is, to provide an additional option for the appearance preferences that allows to use custom styles (scroll all the way down). I also added a class `no-text` that is assigned to labels that contain only whitespace. The following CSS should do what you describe:
```css
.space-bar-workspace-label.active.no-text {
  font-size: 0pt;
  padding: 4px 12px;
  background-color: rgba(255,255,255,1);
}
```

**Comment by DodoLeDev** [comment]
Wow! That works so flawlessly!

![image](https://github.com/user-attachments/assets/1a16fef5-91e6-4856-90f3-4717eb03a888)

Thank you so much for this feature!
