### ISSUE TITLE
conflict with user themes

### ISSUE THREAD

**Issue by FGYada1984** [christopher-l/space-bar#48]
Apparently after the last update there is a conflict with the "user themes" shell extension. when space-bar is active user themes gives the error `Gio.IOErrorEnum: Error opening file /tmp/.TVTPV2: No such file or directory` as reported here: 

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/530

When deactivating the space-bar, the UserThemes function reloads normally after logout/login.

OS: Arch Linux x86_64
DE: GNOME 47.0

**Comment by FGYada1984** [comment]
update (v30) that fixes the problem, I've tested it and everything works normally again. thank you very much!

**Comment by christopher-l** [comment]
Nice :)

Thanks for reporting and testing!
