### ISSUE TITLE
Request: previous workspace switch behaviour like QTile (scripted) and XFCE

### ISSUE THREAD

**Issue by RikRoos** [christopher-l/space-bar#50]
Hi,

I am using Gnome and 'space bar' for a few days now and I am glad having your extension installed, that's for sure :-)

_The casus:_ 
Often I switch between 2 same workspaces that are related together.
I know that SpaceBar offers a separate shortcut for this switching back behaviour.

 I would find it an improvement when pressing the shortcut of the _currently selected workspace_ again, this would bring me back to the previous workspace. Then pressing again, focus would be restored to this same workspace again.
 
 This way I can toggle very fast between 2 workspaces while reading, my fingers hover then above the very same shortcut-keys of the last selected workspace all the time, no need to for remembering numbers or pressing the separate switch-back shortcut.

_Example:_ 
Workspace 2 contains a KiCad apllication screen and workspace 8 contains Firefox with some KiCad help text. 
Workspace 2 is currently active. 
Now I press shortcut for workspace 8 and release it, workspace 8 is now focused.
 I read  quickly some instructions but keeping my fingers above the shortcut keys for workspace 8. Now I want to return to the previous workspace and maybe I don't remember that number.  
But by pressing again the shortcut for the last selected workspace (no 8 in this case) the focus will be transfered back to the previous workspace 2.   

Edit: for QTile I added some Python-code to the config-file to establish this behaviour.

**Comment by christopher-l** [comment]
Hi @RikRoos!

I also thought about this. I'm not sure exactly when I will have the time, but I think this could be useful. Thanks for the request!

**Comment by RikRoos** [comment]
:+1:

**Comment by RikRoos** [comment]
I think the currently implemented separate shortcut for switching back will still have added value in the feature. So, if you will implement this new request then consider to maintain the current implementation also.

**Comment by christopher-l** [comment]
I added a toggle to the shortcut settings for "Switch-to-workspace".
![image](https://github.com/user-attachments/assets/b21777e3-bd86-48b5-9bed-aa626c397d34)

When the change gets approved, the extension should update automatically.

**Comment by RikRoos** [comment]
Hi,
This behaviour of repeating the pressing of a workspace-shortcut is great. I have switched of the behaviour 'Toggle overview' to prevend showing up the 'activities  view'.

However, this new 'back and forth' behaviour does not work for my **workspaces 3 and 8**. Maybe that has something to do with my local config but perhaps you can verify if this is a bug?

**Comment by christopher-l** [comment]
Hi, I cannot reproduce the problem with these particular workspace numbers.

Sometimes colliding key bindings can cause strange behavior. You could check if the back-and-forth behavior works when clicking the workspaces with the mouse.

You can also run the following command while reproducing the problem or disabling / enabling the extension and see if anything comes up:

    journalctl -f -o cat /usr/bin/gnome-shell

**Comment by RikRoos** [comment]
I tried the test with de **mouse-pointer** on all my workspaces and that **functions properly**. So, I looked into _'dconf /org/gnome/desktop/wm/keybindings/'_ and found that al my previous DIY key-bindings for switching to the workspaces (super+[1..9]) were still there. I removed those and now these workspaces 3 and 8 are responding to the 'forth and back' binding.

Thanks for your assistance and this implementation!  Great!
