### ISSUE TITLE
Shortcut to rearrange workspaces and an option to enable/disable middle-click to close a workspace

### ISSUE THREAD

**Issue by emanuelserpa** [christopher-l/space-bar#8]
It would be cool if the shortcut could be Ctrl+Shift+number (or something like this), the command would change the current workspace X to the position Y (number) and the other would be rearranged to X. 

Disable middle-click to "remove" a workspace would be very nice to people that use Thinkpads, for example, I was really unaware about this behaviour and I still sometimes middle click accidentally and the workspace is gone.

Thanks for the great extension!

**Comment by christopher-l** [comment]
Hey @emanuelserpa thanks for the feedback.

For now, I removed the middle-click-to-remove-workspace feature entirely, as I was hardly using it at all and most people probably didn't even realize it was there. If someone misses it, I might add it back with a preference option to disable it.

I might come back on the idea of having a shortcut for rearranging workspaces. For implementing your suggestion of something+number shortcuts, I think some options to what "something" is might be useful. Have to think about how to implement that. An easier-to-implement set of shortcuts would just move a workspace up or down the list, but I take it, you would prefer to move it to a specific number with one shortcut?

**Comment by emanuelserpa** [comment]
>An easier-to-implement set of shortcuts would just move a workspace up or down the list

To be honest, this solution would feel more natural, and I would prefer to my original suggestion. What I don't know is what would be the best shortcut for this.

**Comment by christopher-l** [comment]
I implemented configurable shortcuts for moving the current workspace left or right with the upcoming release (v21).
